name: Publish Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read
  packages: write
  id-token: write
  checks: write
  issues: write
  pull-requests: write

jobs:
  build-releases:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Compute the version tag
    - name: Compute Tag
      id: compute_tag
      uses: craig-day/compute-tag@v18
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        version_type: patch

    # Install the .NET SDK workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore
      working-directory: src

    - name: Build
      run: dotnet build --configuration Release
      working-directory: src

    - name: Publish
      run: dotnet publish TwitterSky\TwitterSky.csproj --configuration Release --no-restore --output ./publish
      working-directory: src

    - name: Create release directory
      run: mkdir -p release

    - name: Create Release Packages zip
      run: Compress-Archive -Path src\publish -DestinationPath release/publish.zip

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        body: ${{ steps.extract_commands.outputs.commands }}
        files: release/*.zip
        tag_name: ${{ steps.compute_tag.outputs.next_tag }}
        prerelease: false
        generate_release_notes: true
        name: TwitterSky ${{ steps.compute_tag.outputs.next_tag }}.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    